=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/xsd/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unequipSkillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="capsuledItemsType">
		<xs:sequence>
			<xs:element name="item" type="capsuledItemType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="level" type="xs:positiveInteger" use="required" />
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NORMAL" />
					<xs:enumeration value="ON_ENCHANT" />
					<xs:enumeration value="ON_EQUIP" />
					<xs:enumeration value="ON_UNEQUIP" />
					<xs:enumeration value="ON_CRITICAL_SKILL" />
					<xs:enumeration value="ON_MAGIC_SKILL" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type_chance" type="xs:positiveInteger" />
		<xs:attribute name="type_value" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="capsuledItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="min" type="xs:positiveInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
		<xs:attribute name="minEnchant" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="maxEnchant" type="xs:positiveInteger" use="optional" />
	</xs:complexType>

	<xs:complexType name="createItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="count" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
	</xs:complexType>

	<xs:complexType name="setType">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="displayId" />
					<xs:enumeration value="armor_type" />
					<xs:enumeration value="attack_range" />
					<xs:enumeration value="auto_destroy_time" />
					<xs:enumeration value="blessed" />
					<xs:enumeration value="bodypart" />
					<xs:enumeration value="capsuled_items" />
					<xs:enumeration value="change_weaponId" />
					<xs:enumeration value="crystal_count" />
					<xs:enumeration value="crystal_type" />
					<xs:enumeration value="damage_range" />
					<xs:enumeration value="default_action" />
					<xs:enumeration value="duration" />
					<xs:enumeration value="element_enabled" />
					<xs:enumeration value="enchant_enabled" />
					<xs:enumeration value="enchant_limit" />
					<xs:enumeration value="enchant4_skill" />
					<xs:enumeration value="enchanted" />
					<xs:enumeration value="equip_condition" />
					<xs:enumeration value="equip_reuse_delay" />
					<xs:enumeration value="ex_immediate_effect" />
					<xs:enumeration value="extractableCountMin" />
					<xs:enumeration value="extractableCountMax" />
					<xs:enumeration value="etcitem_type" />
					<xs:enumeration value="for_npc" />
					<xs:enumeration value="handler" />
					<xs:enumeration value="icon" />
					<xs:enumeration value="immediate_effect" />
					<xs:enumeration value="is_depositable" />
					<xs:enumeration value="is_destroyable" />
					<xs:enumeration value="is_dropable" />
					<xs:enumeration value="is_freightable" />
					<xs:enumeration value="is_magic_weapon" />
					<xs:enumeration value="is_oly_restricted" />
					<xs:enumeration value="is_event_restricted" />
					<xs:enumeration value="isAppearanceable" />
					<xs:enumeration value="ensoulNormalSlots" />
					<xs:enumeration value="ensoulSpecialSlots" />
					<xs:enumeration value="is_premium" />
					<xs:enumeration value="is_questitem" />
					<xs:enumeration value="is_sellable" />
					<xs:enumeration value="is_stackable" />
					<xs:enumeration value="is_tradable" />
					<xs:enumeration value="is_infinite" />
					<xs:enumeration value="is_commissionable" />
					<xs:enumeration value="is_mailable" />
					<xs:enumeration value="is_clan_depositable" />
					<xs:enumeration value="is_private_storeable" />
					<xs:enumeration value="isAttackWeapon" />
					<xs:enumeration value="isForceEquip" />
					<xs:enumeration value="item_skill" />
					<xs:enumeration value="allow_self_resurrection" />
					<xs:enumeration value="material" />
					<xs:enumeration value="mp_consume" />
					<xs:enumeration value="oncrit_chance" />
					<xs:enumeration value="oncrit_skill" />
					<xs:enumeration value="onmagic_chance" />
					<xs:enumeration value="onmagic_skill" />
					<xs:enumeration value="price" />
					<xs:enumeration value="random_damage" />
					<xs:enumeration value="recipe_id" />
					<xs:enumeration value="reduced_mp_consume" />
					<xs:enumeration value="reduced_soulshot" />
					<xs:enumeration value="reuse_delay" />
					<xs:enumeration value="shared_reuse_group" />
					<xs:enumeration value="soulshots" />
					<xs:enumeration value="spiritshots" />
					<xs:enumeration value="time" />
					<xs:enumeration value="unequip_skill" />
					<xs:enumeration value="use_condition" />
					<xs:enumeration value="useSkillDisTime" />
					<xs:enumeration value="useWeaponSkillsOnly" />
					<xs:enumeration value="weapon_type" />
					<xs:enumeration value="weight" />
					<xs:enumeration value="commissionItemType" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="val" type="xs:token" use="required" />
	</xs:complexType>
	<xs:complexType name="playerType">
		<xs:attribute name="castle">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="9" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isOnSide" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NEUTRAL" />
					<xs:enumeration value="LIGHT" />
					<xs:enumeration value="DARK" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isClanLeader" type="xs:boolean" />
		<xs:attribute name="clanHall" type="xs:normalizedString" />
		<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
		<xs:attribute name="cloakStatus" type="xs:boolean" />
		<xs:attribute name="isHero" type="xs:boolean" />
		<xs:attribute name="isPvpFlagged" type="xs:boolean" />
		<xs:attribute name="insideZoneId" type="xs:normalizedString" />
		<xs:attribute name="level">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="pledgeClass">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="11" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="races" type="xs:token" />
		<xs:attribute name="sex" type="xs:byte" use="optional" />
		<xs:attribute name="fort" type="xs:integer" />
		<xs:attribute name="chaotic" type="xs:boolean" />
		<xs:attribute name="subclass" type="xs:boolean" />
		<xs:attribute name="SiegeZone" type="xs:positiveInteger" />
		<xs:attribute name="flyMounted" type="xs:boolean" />
		<xs:attribute name="instanceId" type="xs:normalizedString" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
		<xs:attribute name="pkCount" type="xs:int" />
		<xs:attribute name="vehicleMounted" type="xs:boolean" />
		<xs:attribute name="MinimumVitalityPoints" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="andType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
			<xs:element name="not" type="notType" />
			<xs:element name="game" type="gameType" />
			<xs:element name="or" minOccurs="0" type="andType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="gameType">
		<xs:attribute type="xs:string" name="night" />
	</xs:complexType>
	<xs:complexType name="notType">
		<xs:sequence>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="target" minOccurs="0" type="targetType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usingType">
		<xs:attribute type="xs:string" name="kind" use="optional" />
		<xs:attribute type="xs:string" name="slot" use="optional" />
		<xs:attribute type="xs:string" name="weaponChange" use="optional" />
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
	</xs:complexType>
	<xs:complexType name="enchantType">
		<xs:attribute name="order" type="xs:byte" use="optional" />
		<xs:attribute name="stat" use="required" type="statType" />
		<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
	</xs:complexType>
	<xs:simpleType name="statType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="mDef" />
			<xs:enumeration value="pAtk" />
			<xs:enumeration value="pDef" />
			<xs:enumeration value="sDef" />
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="pAtkAngle" />
			<xs:enumeration value="pAtkRange" />
			<xs:enumeration value="pAtkSpd" />
			<xs:enumeration value="rCrit" />
			<xs:enumeration value="mCritRate" />
			<xs:enumeration value="rShld" />
			<xs:enumeration value="rEvas" />
			<xs:enumeration value="mEvas" />
			<xs:enumeration value="accCombat" />
			<xs:enumeration value="accMagic" />
			<xs:enumeration value="darkRes" />
			<xs:enumeration value="earthRes" />
			<xs:enumeration value="fireRes" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="holyRes" />
			<xs:enumeration value="maxMp" />
			<xs:enumeration value="waterRes" />
			<xs:enumeration value="windRes" />
			<xs:enumeration value="magicSuccRes" />
			<xs:enumeration value="moveSpeed" />
			<xs:enumeration value="broochJewels" />
			<xs:enumeration value="inventoryLimit" />
			<xs:enumeration value="randomDamage" />
			<xs:enumeration value="firePower" />
			<xs:enumeration value="waterPower" />
			<xs:enumeration value="windPower" />
			<xs:enumeration value="earthPower" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="darkPower" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="condType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="and" type="andType" />
			<xs:element name="not" type="notType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="msgId" use="optional" />
		<xs:attribute type="xs:byte" name="addName" use="optional" />
		<xs:attribute type="xs:string" name="msg" use="optional" />
	</xs:complexType>
	<xs:complexType name="forType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="stat" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute type="statType" name="type" use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="enchant" maxOccurs="2" minOccurs="0" type="enchantType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="set" maxOccurs="unbounded" minOccurs="1" type="setType" />
			<xs:element name="unequip_skills" minOccurs="0" type="skillsType" />
			<xs:element name="capsuled_items" minOccurs="0" type="capsuledItemsType" />
			<xs:element name="cond" maxOccurs="2" minOccurs="0" type="condType" />
			<xs:element name="skills" minOccurs="0" type="skillsType" />
			<xs:element name="stats" maxOccurs="1" minOccurs="0" type="forType" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" type="xs:normalizedString" use="required" />
		<xs:attribute name="additionalName" type="xs:normalizedString" use="optional" />
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="Armor" />
					<xs:enumeration value="EtcItem" />
					<xs:enumeration value="Weapon" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/47900-47999.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="47927" name="Magic Fan - Blue" additionalName="Sealed" type="Weapon">
		<!-- A magic fan that can be used for making fire and cooling in hot weather. A beautiful accessory for every costume. <font color=ff6666><Unavailable to Sylphs/ Vanguard Riders/ Assassins.></font> -->
		<set name="icon" val="icon.ev_kr_13th_present_blue" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="BLUNT" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_magic_weapon" val="true" />
		<set name="is_freightable" val="true" />
		<set name="weight" val="150" />
		<stats>
			<stat type="pAtk">1</stat>
			<stat type="mAtk">1</stat>
			<stat type="rCrit">6</stat>
			<stat type="accCombat">8</stat>
			<stat type="pAtkSpd">379</stat>
			<stat type="randomDamage">1</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
	<item id="47928" name="Magic Woodpile" type="EtcItem">
		<!-- Double-click to use a magic woodpile for one player. If you have the Magic Fan equipped, you can use the skills Breeze and Gust to set fire to the woodpile. -->
		<set name="icon" val="icon.ev_firewood_seed_solo" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="is_stackable" val="true" />
		<set name="material" val="WOOD" />
	</item>
	<item id="47929" name="Large Magic Woodpile" type="EtcItem">
		<!-- Double-click to use a magic woodpile for party use. If you have the Magic Fan equipped, you can use the skills Breeze and Gust to set fire to the woodpile. -->
		<set name="icon" val="icon.ev_firewood_seed_party" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="is_stackable" val="true" />
		<set name="material" val="WOOD" />
	</item>
	<item id="47945" name="Magic Fan - Yellow" additionalName="Sealed" type="Weapon">
		<!-- A magic fan that can be used for making fire and cooling in hot weather. A beautiful accessory for every costume. <font color=ff6666><Unavailable to Sylphs/ Vanguard Riders/ Assassins.></font> -->
		<set name="icon" val="icon.ev_kr_13th_present_yellow" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="BLUNT" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_magic_weapon" val="true" />
		<set name="is_freightable" val="true" />
		<set name="weight" val="150" />
		<stats>
			<stat type="pAtk">1</stat>
			<stat type="mAtk">1</stat>
			<stat type="rCrit">6</stat>
			<stat type="accCombat">8</stat>
			<stat type="pAtkSpd">379</stat>
			<stat type="randomDamage">1</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/39700-39799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="39719" name="Monster Only: Kruk's Staff" additionalName="Sealed" type="Weapon">
		<!-- Monster weapon. -->
		<set name="icon" val="icon.wp_fishing4" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="POLE" />
		<set name="bodypart" val="lrhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="D" />
		<set name="material" val="STEEL" />
		<set name="weight" val="205" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_destroyable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<stats>
			<stat type="pAtk">92</stat>
			<stat type="mAtk">54</stat>
			<stat type="rCrit">8</stat>
			<stat type="accCombat">-3.75</stat>
			<stat type="pAtkSpd">325</stat>
			<stat type="randomDamage">10</stat>
			<stat type="pAtkRange">80</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/99300-99399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="99357" name="Emerald Weapon: Rapier" type="Weapon">
		<set name="icon" val="BranchSys3.Icon.g_beam_sword" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="RAPIER" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="B" />
		<set name="material" val="STEEL" />
		<set name="weight" val="144" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_sellable" val="false" />
		<set name="is_freightable" val="true" />
		<stats>
			<stat type="randomDamage">10</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/33700-33799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="33778" name="A-grade Soulshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Soulshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SOULSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="33785" name="A-grade Spiritshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Spiritshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SPIRITSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="33792" name="Blessed A-grade Spiritshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Spiritshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SPIRITSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/20600-20699.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="20662" name="Agathion Uthanka" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A bracelet for summoning Uthanka. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="lbracelet" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="SILVER" />
		<set name="weight" val="150" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="is_freightable" val="true" />
		<skills>
			<skill id="21109" level="1" type="ON_EQUIP" /> <!-- Release Agathion's Seal - Uthanka -->
			<skill id="23087" level="1" /> <!-- Uthanka Agathion Cute Trick -->
			<skill id="3267" level="1" type="ON_UNEQUIP" /> <!-- Seal Agathion -->
		</skills>
	</item>
	<item id="20666" name="Valkyrie Hat" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A hat endowed with the Valkyrie's power. <font color=eeaa22>Equipped in the left head accessory slot.</font> -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="isAppearanceable" val="true" />
	</item>
	<item id="20678" name="Gatekeeper Hat" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A hat worn by Gatekeepers. <font color=eeaa22>Equipped in the left head accessory slot.</font> -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="isAppearanceable" val="true" />
	</item>
</list>
